name: Publish mcp-server (npm)

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Verify tag equals mcp-server version
        working-directory: mcp-server
        run: |
          TAG="${{ github.event.release.tag_name }}"
          PKG_VER=$(node -p "require('./package.json').version")
          echo "tag: $TAG / package: $PKG_VER"
          if [ "v$PKG_VER" != "$TAG" ]; then
            echo "Version mismatch: tag($TAG) != package($PKG_VER)" >&2
            exit 1
          fi

      - name: Ensure csharp-lsp manifest exists in release assets
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG="${{ github.event.release.tag_name }}"
          REPO="${{ github.repository }}"
          # Fetch assets list
          JSON=$(gh api repos/$REPO/releases/tags/$TAG)
          echo "$JSON" | jq '.assets[].name'
          if ! echo "$JSON" | jq -r '.assets[].name' | grep -qx 'csharp-lsp-manifest.json'; then
            echo "csharp-lsp-manifest.json not found in release assets for $TAG" >&2
            exit 1
          fi

      - name: Install deps and test
        working-directory: mcp-server
        run: |
          npm ci
          npm run test:ci

      - name: Publish to npm (public)
        working-directory: mcp-server
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm publish --access public
